defaults:
  - nbv_schema
  - _self_

experiment_name: dataset-house3k
batch_size: 4
max_meshes: 20
learning_rate: 1e-5
max_epochs: 500
seed: 42

output_dir: ${hydra:runtime.cwd}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb:
  enabled: true
  project: nbv-framework
  entity: null
  name: ${experiment_name}-${now:%Y%m%d_%H%M%S}
  group: null
  tags: []
  notes: null
  mode: online
  log_model: false

hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: ${hydra:runtime.cwd}/runs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true

trainer:
  accelerator: auto
  devices: auto
  enable_checkpointing: false
  strategy: auto
  precision: 32
  sync_batchnorm: true
  benchmark: true
  max_epochs: ${max_epochs}
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 1
